on: [push, pull_request]

name: Continuous integration

jobs:
  test:
    name: API Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm run test